export type Pseudo =
  // Pseudo-classes (CSS 1–4 + UI states)
  | ":active"
  | ":any-link"
  | ":blank"
  | ":checked"
  | ":default"
  | ":defined"
  | ":disabled"
  | ":empty"
  | ":enabled"
  | ":first"
  | ":first-child"
  | ":first-of-type"
  | ":fullscreen"
  | ":focus"
  | ":focus-visible"
  | ":focus-within"
  | ":has"
  | ":hover"
  | ":in-range"
  | ":indeterminate"
  | ":invalid"
  | ":lang"
  | ":last-child"
  | ":last-of-type"
  | ":link"
  | ":not"
  | ":nth-child"
  | ":nth-last-child"
  | ":nth-last-of-type"
  | ":nth-of-type"
  | ":only-child"
  | ":only-of-type"
  | ":optional"
  | ":out-of-range"
  | ":placeholder-shown"
  | ":read-only"
  | ":read-write"
  | ":required"
  | ":root"
  | ":scope"
  | ":target"
  | ":valid"
  | ":visited"

  // Pseudo-elements (CSS 2.1–4)
  | "::after"
  | "::before"
  | "::cue"
  | "::first-letter"
  | "::first-line"
  | "::grammar-error"
  | "::marker"
  | "::placeholder"
  | "::selection"
  | "::slotted"
  | "::target-text"
  | "::backdrop"
  | "::file-selector-button"
  | "::part"
  | "::spelling-error"
  | "::cue-region"

  // Vendor or custom prefixes
  | ":-moz-focusring"
  | ":-moz-full-screen"
  | ":-moz-placeholder"
  | ":-ms-input-placeholder"
  | ":-webkit-autofill"
  | ":-webkit-full-screen"
  | ":-webkit-autofill"
  | `:-${string}` // catch-all for any other custom/vendor pseudos
  | `::${string}`; // catch-all for any other pseudo-elements
